<a href="https://colab.research.google.com/github/Zaki2409/AI-Engineer-Hands-on/blob/master/Pytorch_NN_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy pandas torch scikit-learn

In [26]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [27]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [28]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [29]:
df.shape

(569, 33)

In [30]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [31]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [61]:
#df.iloc[0]
#df.iloc[:] = df.head()
# all expect the target for x train and x test df.iloc[:,1:]
# only the target for y test and y train df.iloc[:,0]

In [62]:
df_test, df_train = train_test_split(df, test_size=0.2)

In [64]:
df_test.shape

(455, 31)

In [65]:
df_train.shape

(114, 31)

In [67]:
X_train = df_train.iloc[:,1:]
Y_train = df_train.iloc[:,0]

In [69]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
370,16.35,23.29,109.00,840.4,0.09742,0.14970,0.181100,0.08773,0.2175,0.06218,...,19.38,31.03,129.30,1165.0,0.14150,0.46650,0.70870,0.22480,0.4824,0.09614
233,20.51,27.81,134.40,1319.0,0.09159,0.10740,0.155400,0.08340,0.1448,0.05592,...,24.47,37.38,162.70,1872.0,0.12230,0.27610,0.41460,0.15630,0.2437,0.08328
171,13.43,19.63,85.84,565.4,0.09048,0.06288,0.058580,0.03438,0.1598,0.05671,...,17.98,29.87,116.60,993.6,0.14010,0.15460,0.26440,0.11600,0.2884,0.07371
305,11.60,24.49,74.23,417.2,0.07474,0.05688,0.019740,0.01313,0.1935,0.05878,...,12.44,31.62,81.39,476.5,0.09545,0.13610,0.07239,0.04815,0.3244,0.06745
380,11.27,12.96,73.16,386.3,0.12370,0.11110,0.079000,0.05550,0.2018,0.06914,...,12.84,20.53,84.93,476.1,0.16100,0.24290,0.22470,0.13180,0.3343,0.09215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,11.27,15.50,73.38,392.0,0.08365,0.11140,0.100700,0.02757,0.1810,0.07252,...,12.04,18.93,79.73,450.0,0.11020,0.28090,0.30210,0.08272,0.2157,0.10430
8,13.00,21.82,87.50,519.8,0.12730,0.19320,0.185900,0.09353,0.2350,0.07389,...,15.49,30.73,106.20,739.3,0.17030,0.54010,0.53900,0.20600,0.4378,0.10720
53,18.22,18.70,120.30,1033.0,0.11480,0.14850,0.177200,0.10600,0.2092,0.06310,...,20.60,24.13,135.10,1321.0,0.12800,0.22970,0.26230,0.13250,0.3021,0.07987
179,12.81,13.06,81.29,508.8,0.08739,0.03774,0.009193,0.01330,0.1466,0.06133,...,13.63,16.15,86.70,570.7,0.11620,0.05445,0.02758,0.03990,0.1783,0.07319


In [70]:
Y_train

,diagnosis
370,M
233,M
171,M
305,B
380,B
...,...
388,B
8,M
53,M
179,B


In [71]:
X_test = df_test.iloc[:,1:]
Y_test = df_test.iloc[:,0]

In [72]:
X_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
296,10.910,12.35,69.14,363.7,0.08518,0.04721,0.01236,0.01369,0.1449,0.06031,...,11.37,14.82,72.42,392.2,0.09312,0.07506,0.02884,0.03194,0.2143,0.06643
155,12.250,17.94,78.27,460.3,0.08654,0.06679,0.03885,0.02331,0.1970,0.06228,...,13.59,25.22,86.60,564.2,0.12170,0.17880,0.19430,0.08211,0.3113,0.08132
84,12.000,15.65,76.95,443.3,0.09723,0.07165,0.04151,0.01863,0.2079,0.05968,...,13.67,24.90,87.78,567.9,0.13770,0.20030,0.22670,0.07632,0.3379,0.07924
230,17.050,19.08,113.40,895.0,0.11410,0.15720,0.19100,0.10900,0.2131,0.06325,...,19.59,24.89,133.50,1189.0,0.17030,0.39340,0.50180,0.25430,0.3109,0.09061
505,9.676,13.14,64.12,272.5,0.12550,0.22040,0.11880,0.07038,0.2057,0.09575,...,10.60,18.04,69.47,328.1,0.20060,0.36630,0.29130,0.10750,0.2848,0.13640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,14.020,15.66,89.59,606.5,0.07966,0.05581,0.02087,0.02652,0.1589,0.05586,...,14.91,19.31,96.53,688.9,0.10340,0.10170,0.06260,0.08216,0.2136,0.06710
124,13.370,16.39,86.10,553.5,0.07115,0.07325,0.08092,0.02800,0.1422,0.05823,...,14.26,22.75,91.99,632.1,0.10250,0.25310,0.33080,0.08978,0.2048,0.07628
210,20.580,22.14,134.70,1290.0,0.09090,0.13480,0.16400,0.09561,0.1765,0.05024,...,23.24,27.84,158.30,1656.0,0.11780,0.29200,0.38610,0.19200,0.2909,0.05865
489,16.690,20.20,107.10,857.6,0.07497,0.07112,0.03649,0.02307,0.1846,0.05325,...,19.18,26.56,127.30,1084.0,0.10090,0.29200,0.24770,0.08737,0.4677,0.07623


In [73]:
Y_test

,diagnosis
296,B
155,B
84,B
230,M
505,B
...,...
439,B
124,B
210,M
489,M


In [74]:
scale= StandardScaler()
X_train = scale.fit_transform(X_train)
X_test = scale.fit_transform(X_test)

In [76]:
X_train

array([[ 0.56125297,  1.12219186,  0.62433739, ...,  1.56141486,
         3.04369556,  0.48846176],
       [ 1.69309547,  2.2828563 ,  1.62607249, ...,  0.55495678,
        -0.72089747, -0.09355719],
       [-0.2332134 ,  0.18236181, -0.28905572, ..., -0.03716381,
        -0.01592341, -0.52667706],
       ...,
       [ 1.07003794, -0.05644747,  1.0699912 , ...,  0.2052677 ,
         0.20014247, -0.24788726],
       [-0.40190146, -1.50471017, -0.4685004 , ..., -1.15528731,
        -1.75233603, -0.55021126],
       [ 0.17218211, -1.02452378,  0.1293856 , ..., -0.05626447,
        -0.32503955, -0.11844914]])

In [78]:
X_test

array([[-0.912993  , -1.60278991, -0.93905375, ..., -1.2561635 ,
        -1.23672198, -1.01802231],
       [-0.52793816, -0.32872797, -0.55848541, ..., -0.48462586,
         0.34292265, -0.1349105 ],
       [-0.59977675, -0.85066032, -0.61350734, ..., -0.57366718,
         0.77610355, -0.25827333],
       ...,
       [ 1.86572363,  0.62852788,  1.79370206, ...,  1.20531377,
         0.01070873, -1.47944675],
       [ 0.74791518,  0.18636684,  0.64324355, ..., -0.40373513,
         2.88989605, -0.43679358],
       [-0.78080999, -0.11220581, -0.81275341, ..., -0.79342546,
         0.59371159, -0.80984753]])

In [82]:
encoder = LabelEncoder()
Y_train = encoder.fit_transform(Y_train)
Y_test = encoder.fit_transform(Y_test)

In [83]:
Y_train

array([0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,

In [84]:
Y_test

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1])

CONVERT NUMPY TO TENSOR TO USE GPU

In [85]:
X_train_tensor = torch.from_numpy(X_train)
Y_train_tensor = torch.from_numpy(Y_train)
X_test_tensor = torch.from_numpy(X_test)
Y_test_tensor = torch.from_numpy(Y_test)


In [86]:
X_train_tensor.shape

torch.Size([114, 30])

In [88]:
X_test_tensor.shape

torch.Size([455, 30])

In [89]:
Y_test_tensor.shape

torch.Size([114])

In [90]:
Y_train_tensor.shape

torch.Size([455])

#DEFINING A MODEL

In [91]:
class MyNN():
  def __init__(self,X):

    self.weights = torch.rand(X.shape[1], 1, dtype= torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype= torch.float64, requires_grad=True)

  def forward(self,X):
    z=  torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon, 1-epsilon)

    loss = -(Y_train_tensor * torch.log(y_pred) + (1 - Y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


IMPORTATN PAPRAMS

In [92]:
learning_rate = 0.1
epochs = 25

TRAINING PARAMETER

In [93]:
# create model
model = MyNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, Y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.0949221939808256
Epoch: 2, Loss: 2.9851845164988973
Epoch: 3, Loss: 2.872262019739579
Epoch: 4, Loss: 2.7597890726127745
Epoch: 5, Loss: 2.63780171566093
Epoch: 6, Loss: 2.512710377191976
Epoch: 7, Loss: 2.388926261238637
Epoch: 8, Loss: 2.2518608035965584
Epoch: 9, Loss: 2.1009022918658617
Epoch: 10, Loss: 1.9532607689049588
Epoch: 11, Loss: 1.79844133401588
Epoch: 12, Loss: 1.652094300118549
Epoch: 13, Loss: 1.5154531740081483
Epoch: 14, Loss: 1.3898320271360722
Epoch: 15, Loss: 1.276442660041671
Epoch: 16, Loss: 1.1762099843169098
Epoch: 17, Loss: 1.0896364144611472
Epoch: 18, Loss: 1.0167042349911988
Epoch: 19, Loss: 0.9568497110403452
Epoch: 20, Loss: 0.9090490063553177
Epoch: 21, Loss: 0.8719322926583977
Epoch: 22, Loss: 0.8438397411438876
Epoch: 23, Loss: 0.8228905540834067
Epoch: 24, Loss: 0.8071785019368488
Epoch: 25, Loss: 0.7950428104224784


In [94]:
model.bias

tensor([-0.1393], dtype=torch.float64, requires_grad=True)

In [96]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6335647106170654
