<a href="https://colab.research.google.com/github/Zaki2409/AI-Engineer-Hands-on/blob/master/Training_model_using_nn_module_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):
  def __init__ (self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.Sigmoid = nn.Sigmoid()
  def forward (self,features):
    out = self.linear(features)
    out = self.Sigmoid(out)
    return out

In [3]:
#dataset
feature = torch.rand(10,5)

In [5]:
#model instacne
model = Model(feature.shape[1])

In [6]:
#foraward call
model(feature)


tensor([[0.5222],
        [0.4758],
        [0.5538],
        [0.5119],
        [0.5006],
        [0.5151],
        [0.4296],
        [0.4894],
        [0.5005],
        [0.5038]], grad_fn=<SigmoidBackward0>)

In [7]:
#print model weights
model.linear.weight

Parameter containing:
tensor([[-0.3178,  0.1913,  0.2834,  0.4414, -0.2006]], requires_grad=True)

In [8]:
#print model bias
model.linear.bias

Parameter containing:
tensor([-0.1443], requires_grad=True)

In [9]:
# to visualize the network
!pip install torchinfo

In [10]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00