<a href="https://colab.research.google.com/github/Zaki2409/AI-Engineer-Hands-on/blob/master/Training_model_using_nn_module_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn

In [3]:
class Model(nn.Module):
  def __init__ (self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.Sigmoid = nn.Sigmoid()
  def forward (self,features):
    out = self.linear(features)
    out = self.Sigmoid(out)
    return out

In [4]:
class Model2(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [24]:
class Model2a(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )
  def forward(self, features):
      out = self.network(features)
      return out

In [25]:
#dataset
feature = torch.rand(10,5)

In [26]:
#model instacne
model = Model(feature.shape[1])
model2 = Model2(feature.shape[1])
model2a = Model2a(feature.shape[1])

In [27]:
#foraward call
model(feature)


tensor([[0.4772],
        [0.5174],
        [0.4195],
        [0.5301],
        [0.3989],
        [0.4577],
        [0.3832],
        [0.4519],
        [0.4340],
        [0.4564]], grad_fn=<SigmoidBackward0>)

In [28]:
model2(feature)


tensor([[0.5005],
        [0.5003],
        [0.5356],
        [0.5174],
        [0.5225],
        [0.5191],
        [0.5407],
        [0.5186],
        [0.5350],
        [0.5183]], grad_fn=<SigmoidBackward0>)

In [29]:
model2a(feature)


tensor([[0.5574],
        [0.5602],
        [0.5631],
        [0.5712],
        [0.5588],
        [0.5561],
        [0.5577],
        [0.5556],
        [0.5724],
        [0.5749]], grad_fn=<SigmoidBackward0>)

In [30]:
#print model weights
model.linear.weight

Parameter containing:
tensor([[-0.2579,  0.1655, -0.0038, -0.4273,  0.1993]], requires_grad=True)

In [31]:
#print model bias
model.linear.bias

Parameter containing:
tensor([0.0206], requires_grad=True)

In [32]:
model2.linear1.weight

Parameter containing:
tensor([[-0.0129, -0.0061, -0.3548,  0.1531,  0.2393],
        [ 0.0471, -0.4162, -0.2463,  0.2675, -0.1831],
        [ 0.0509,  0.0496,  0.3053,  0.0766,  0.3429]], requires_grad=True)

In [33]:
model2.linear2.weight

Parameter containing:
tensor([[0.4103, 0.4657, 0.3487]], requires_grad=True)

In [34]:
model2.linear1.bias

Parameter containing:
tensor([-0.2200,  0.3590,  0.4418], requires_grad=True)

In [35]:
model2.linear1.bias

Parameter containing:
tensor([-0.2200,  0.3590,  0.4418], requires_grad=True)

In [38]:
model2a.network[0].weight

Parameter containing:
tensor([[ 0.1560, -0.0518, -0.2593, -0.0247,  0.0369],
        [-0.0594,  0.3526, -0.1920, -0.1851,  0.1711],
        [ 0.1250, -0.3424, -0.0360, -0.2339,  0.3330]], requires_grad=True)

In [39]:
model2a.network[0].bias

Parameter containing:
tensor([ 0.3816, -0.2734,  0.0509], requires_grad=True)

In [40]:
model2a.network[0].weight

Parameter containing:
tensor([[ 0.1560, -0.0518, -0.2593, -0.0247,  0.0369],
        [-0.0594,  0.3526, -0.1920, -0.1851,  0.1711],
        [ 0.1250, -0.3424, -0.0360, -0.2339,  0.3330]], requires_grad=True)

In [42]:
model2a.network[0].bias

Parameter containing:
tensor([ 0.3816, -0.2734,  0.0509], requires_grad=True)

In [43]:
# to visualize the network
!pip install torchinfo

In [44]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [45]:
from torchinfo import summary
summary(model2, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [46]:
from torchinfo import summary
summary(model2a, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2a                                  [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00