<a href="https://colab.research.google.com/github/Zaki2409/AI-Engineer-Hands-on/blob/master/Training_model_using_nn_module_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [5]:
class Model(nn.Module):
  def __init__ (self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.Sigmoid = nn.Sigmoid()
  def forward (self,features):
    out = self.linear(features)
    out = self.Sigmoid(out)
    return out

In [10]:
class Model2(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [11]:
#dataset
feature = torch.rand(10,5)

In [12]:
#model instacne
model = Model(feature.shape[1])
model2 = Model2(feature.shape[1])

In [14]:
#foraward call
model(feature)


tensor([[0.6058],
        [0.6559],
        [0.6048],
        [0.6302],
        [0.6547],
        [0.6022],
        [0.6256],
        [0.5903],
        [0.6597],
        [0.6231]], grad_fn=<SigmoidBackward0>)

In [15]:
model2(feature)


tensor([[0.4684],
        [0.4719],
        [0.4707],
        [0.4623],
        [0.4213],
        [0.4748],
        [0.4663],
        [0.4712],
        [0.4655],
        [0.4737]], grad_fn=<SigmoidBackward0>)

In [16]:
#print model weights
model.linear.weight

Parameter containing:
tensor([[ 0.0936,  0.3383, -0.0156,  0.3285,  0.2152]], requires_grad=True)

In [17]:
#print model bias
model.linear.bias

Parameter containing:
tensor([0.0574], requires_grad=True)

In [19]:
model2.linear1.weight

Parameter containing:
tensor([[-0.4093,  0.4442, -0.2531, -0.1667, -0.1961],
        [ 0.2008,  0.4441, -0.2492, -0.2128,  0.2371],
        [-0.4254,  0.1035,  0.1919,  0.1497, -0.2353]], requires_grad=True)

In [20]:
model2.linear2.weight

Parameter containing:
tensor([[-0.4815, -0.0981, -0.1650]], requires_grad=True)

In [21]:
model2.linear1.bias

Parameter containing:
tensor([ 0.1471,  0.0542, -0.0486], requires_grad=True)

In [22]:
model2.linear1.bias

Parameter containing:
tensor([ 0.1471,  0.0542, -0.0486], requires_grad=True)

In [24]:
# to visualize the network
!pip install torchinfo

In [25]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [26]:
from torchinfo import summary
summary(model2, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00